package com.ifba.iotManagement.audit;

public enum AuditAction {
    RESOURCE_CREATED,
    RESOURCE_UPDATED, 
    RESOURCE_DELETED,
    RESOURCE_STATUS_UPDATED,
    RESERVE_CREATED,
    RESERVE_RELEASED,
    RESERVE_EXPIRED,
    USER_LOGIN,
    USER_CREATED,
    USER_UPDATED,
    DEVICE_STATUS_UPDATE,
    DEVICE_COMMAND_SENT,
    DEVICE_AUTO_RELEASE
}